plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0

title: "Speed Up Validator Setup"
description: "A simple guide to setting up a validator"
show_downloads: false
google_analytics: false  # If you have an analytics ID, replace `false` with your ID, e.g., 'UA-XXXXX-Y'

# Optimize for mobile
mobile_optimization: true
